import {
  Body, Controller, Delete, Get, HttpCode, Inject, Post,
} from '@nestjs/common';
import { IsIn, IsString, MinLength } from 'class-validator';
import { Pool } from 'pg';
import { PG_POOL } from '../../common/db/db.module';
import { LineNotifier } from './line.notifier';
import { LineRichMenuService } from './line-rich-menu.service';
import { FcmService } from './fcm.service';
import { CurrentUser } from '../../common/auth/current-user.decorator';
import type { CurrentUser as CU } from '../../common/auth/current-user.decorator';

class RegisterFcmTokenDto {
  @IsString() @MinLength(10)
  token!: string;

  @IsString() @IsIn(['android', 'ios', 'web'])
  platform!: string;
}

class SetupRichMenuDto {
  /** Base64-encoded PNG generated by the browser canvas. */
  @IsString() @MinLength(100)
  imageBase64!: string;

  /** Public base URL of the web app, e.g. https://nirvaprocure.com */
  @IsString() @MinLength(7)
  appUrl!: string;
}

@Controller('notifications')
export class NotificationsController {
  constructor(
    private readonly line:     LineNotifier,
    private readonly richMenu: LineRichMenuService,
    private readonly fcm:      FcmService,
    @Inject(PG_POOL) private readonly pool: Pool,
  ) {}

  // ---------------------------------------------------------------------------
  // Test push
  // ---------------------------------------------------------------------------

  @Post('line/test')
  @HttpCode(202)
  async testLine(@CurrentUser() user: CU) {
    await this.line.send({
      user_id: user.userId,
      org_id:  user.orgId,
      template: 'reorder_digest',
      payload:  { count: 0 },
    });
    return { queued: true };
  }

  // ---------------------------------------------------------------------------
  // LINE account binding
  // ---------------------------------------------------------------------------

  @Get('line/status')
  async lineStatus(@CurrentUser() user: CU) {
    const res = await this.pool.query<{ linked: boolean }>(
      `SELECT (line_user_id IS NOT NULL) AS linked
         FROM users WHERE id = $1 AND deleted_at IS NULL`,
      [user.userId],
    );
    return { linked: res.rows[0]?.linked ?? false };
  }

  @Post('line/bind')
  @HttpCode(200)
  async requestBinding(@CurrentUser() user: CU) {
    const code      = String(Math.floor(100_000 + Math.random() * 900_000));
    const expiresAt = new Date(Date.now() + 10 * 60 * 1000);
    await this.pool.query(
      `UPDATE users
          SET line_binding_code = $1, line_binding_expires_at = $2
        WHERE id = $3`,
      [code, expiresAt, user.userId],
    );
    return { code, expires_at: expiresAt.toISOString() };
  }

  @Delete('line/bind')
  @HttpCode(204)
  async unlinkLine(@CurrentUser() user: CU) {
    await this.pool.query(
      `UPDATE users
          SET line_user_id = NULL, line_binding_code = NULL, line_binding_expires_at = NULL
        WHERE id = $1`,
      [user.userId],
    );
  }

  // ---------------------------------------------------------------------------
  // LINE Rich Menu (OA-level — admin only in practice)
  // ---------------------------------------------------------------------------

  /**
   * Returns the current default rich menu id (or null if none is set).
   * GET /notifications/line/rich-menu/status → { richMenuId: string | null }
   */
  @Get('line/rich-menu/status')
  richMenuStatus() {
    return this.richMenu.getStatus();
  }

  /**
   * Create / replace the default rich menu.
   * Accepts a base64 PNG image generated by the browser canvas.
   * POST /notifications/line/rich-menu/setup → { richMenuId: string }
   */
  @Post('line/rich-menu/setup')
  @HttpCode(200)
  async setupRichMenu(@Body() dto: SetupRichMenuDto) {
    return this.richMenu.setup(dto.imageBase64, dto.appUrl);
  }

  /**
   * Remove the current default rich menu from the LINE OA.
   * DELETE /notifications/line/rich-menu → 204
   */
  @Delete('line/rich-menu')
  @HttpCode(204)
  async deleteRichMenu() {
    await this.richMenu.deleteDefault();
  }

  // ---------------------------------------------------------------------------
  // FCM push notifications
  // ---------------------------------------------------------------------------

  @Post('fcm/token')
  @HttpCode(200)
  async registerFcmToken(
    @CurrentUser() user: CU,
    @Body() dto: RegisterFcmTokenDto,
  ) {
    await this.fcm.registerToken(user.userId, dto.token, dto.platform);
    return { registered: true };
  }

  @Delete('fcm/token')
  @HttpCode(204)
  async removeFcmToken(@Body() dto: { token: string }) {
    await this.fcm.removeToken(dto.token);
  }

  @Post('fcm/test')
  @HttpCode(202)
  async testFcm(@CurrentUser() user: CU) {
    const sent = await this.fcm.sendToUser(user.userId, {
      title: 'NirvaProcure',
      body: 'Test push notification 🔔',
      data: { route: '/home' },
    });
    return { sent };
  }
}
