/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List purchase requests */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["PrStatus"];
                    requester_id?: string;
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["PurchaseRequest"][];
                            next_cursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a purchase request (draft) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PrCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pr/import-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse a marketplace product URL into a PR line-item draft
         * @description Accepts a Shopee, Lazada, Alibaba, or Makro product URL. Returns a
         *     line-item draft with description, unit price, supplier name, and
         *     parsed metadata. The client decides whether to attach it to an
         *     existing PR or create a new one.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uri */
                        url: string;
                    };
                };
            };
            responses: {
                /** @description Parsed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ParsedLineItem"];
                    };
                };
                /** @description URL was reachable but could not be parsed */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pr/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a single PR with items and approval trail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseRequestDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update PR fields or line items (draft only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PrUpdate"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseRequest"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/pr/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a draft PR for approval */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Submitted; approval instance created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseRequestDetail"];
                    };
                };
                /** @description PR not in draft status */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List PRs currently awaiting the caller's decision */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApprovalInboxItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{instance_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or reject at the caller's current step */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instance_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        decision: "approved" | "rejected";
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Decision recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseRequestDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/line/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test LINE notification to the caller */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        PrStatus: "draft" | "submitted" | "in_approval" | "approved" | "rejected" | "cancelled" | "completed";
        Money: {
            /** @description Amount in minor units (e.g. satang) */
            amount_minor: number;
            /** @example THB */
            currency: string;
        };
        PrCreate: {
            title: string;
            justification?: string;
            /** Format: uuid */
            department_id?: string;
            items: components["schemas"]["PrLineItemInput"][];
        };
        PrUpdate: {
            title?: string;
            justification?: string;
            /** Format: uuid */
            department_id?: string;
            items?: components["schemas"]["PrLineItemInput"][];
        };
        PrLineItemInput: {
            description: string;
            quantity: number;
            /** @example unit */
            unit?: string;
            unit_price_minor: number;
            /** Format: uuid */
            supplier_id?: string;
            /** @enum {string} */
            source?: "shopee" | "lazada" | "alibaba" | "makro" | "manual";
            /** Format: uri */
            source_url?: string;
            source_metadata?: {
                [key: string]: unknown;
            };
        };
        PurchaseRequest: {
            /** Format: uuid */
            id?: string;
            /** @example PR-2026-0001 */
            pr_number?: string;
            title?: string;
            status?: components["schemas"]["PrStatus"];
            /** Format: uuid */
            requester_id?: string;
            /** Format: uuid */
            department_id?: string | null;
            total?: components["schemas"]["Money"];
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        PurchaseRequestDetail: components["schemas"]["PurchaseRequest"] & {
            justification?: string;
            items?: components["schemas"]["PrLineItem"][];
            approval?: components["schemas"]["ApprovalTrail"];
        };
        PrLineItem: {
            /** Format: uuid */
            id?: string;
            line_no?: number;
            description?: string;
            quantity?: number;
            unit?: string;
            unit_price_minor?: number;
            line_total_minor?: number;
            /** Format: uuid */
            supplier_id?: string | null;
            source?: string | null;
            source_url?: string | null;
        };
        ParsedLineItem: {
            /** @enum {string} */
            source?: "shopee" | "lazada" | "alibaba" | "makro";
            /** Format: uri */
            source_url?: string;
            description?: string;
            unit_price_minor?: number;
            /** @example THB */
            currency?: string;
            supplier?: {
                name?: string;
                external_ref?: string;
            };
            source_metadata?: {
                [key: string]: unknown;
            };
        };
        ApprovalInboxItem: {
            /** Format: uuid */
            instance_id?: string;
            pr?: components["schemas"]["PurchaseRequest"];
            step_no?: number;
            /** Format: date-time */
            waiting_since?: string;
        };
        ApprovalTrail: {
            /** Format: uuid */
            instance_id?: string;
            current_step?: number;
            /** @enum {string} */
            status?: "pending" | "approved" | "rejected" | "cancelled";
            decisions?: {
                step_no?: number;
                /** Format: uuid */
                approver_id?: string;
                /** @enum {string} */
                decision?: "approved" | "rejected";
                comment?: string;
                /** Format: date-time */
                decided_at?: string;
            }[];
        };
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
